version: '3.3'
services:
  mongo_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${ui_version}
    ports:
      - ${PORT}:9292/tcp
    networks:
      - front_net
  post:
    build: ./post-py
    image: ${USERNAME}/post:${post_version}
    networks:
      - back_net
      - front_net
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${comment_version}
    networks:
      - back_net
      - front_net
volumes:
  post_db:

networks:
  back_net:
      ipam:
        config:
          - subnet: ${BACKNET}
  front_net:
      ipam:
        config:
          - subnet: ${FROTNET}

