version: '3.3'
services:
  mongo_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    #build: ./ui
    image: ${USER_NAME}/ui:${ui_version}
    ports:
      - ${PORT}:9292/tcp
    networks:
      - front_net
  post:
    #build: ./post-py
    image: ${USER_NAME}/post:${post_version}
    networks:
      - back_net
      - front_net
  comment:
    #build: ./comment
    image: ${USER_NAME}/comment:${comment_version}
    networks:
      - back_net
      - front_net
  prometheus:
    image: ${USER_NAME}/prometheus
    ports:
      - '9090:${prometheus_port}'
    networks:
      - back_net
      - front_net
  node-exporter:
    image: prom/node-exporter:v0.15.0
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - back_net
  cadvisor:
    image: google/cadvisor:latest
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:rw'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
    ports:
      - '8080:${cadvisor_port}'
    networks:
      - back_net
  grafana:
    image: grafana/grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    depends_on:
      - prometheus
    ports:
      - 3000:${grafana_port}
    networks:
      - back_net
  alertmanager:
    image: ${USER_NAME}/alertmanager
    command:
      - '-config.file=/etc/alertmanager/config.yml'
    ports:
      - 9093:${alertmanager_port}
    networks:
      - back_net

volumes:
  post_db:
  grafana_data:

networks:
  back_net:
      ipam:
        config:
          - subnet: ${BACKNET}
  front_net:
      ipam:
        config:
          - subnet: ${FROTNET}

